steps:
  # Optional: List files for debugging purposes
  - name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - 'ls -la .'
    id: 'ListFiles'

  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - '${_AR_HOSTNAME}/${PROJECT_ID}/cloud-run-source-deploy/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '-f'
      - 'Dockerfile'          # Direct reference since it's in the same directory
      - '.'                    # Build context is the current directory
    id: 'Build'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_AR_HOSTNAME}/${PROJECT_ID}/cloud-run-source-deploy/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'
    id: 'Push'

  # Step 3: Deploy the Docker image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--platform=managed'
      - '--image=${_AR_HOSTNAME}/${PROJECT_ID}/cloud-run-source-deploy/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '--region=${_DEPLOY_REGION}'
      - '--allow-unauthenticated'  # Adjust based on your authentication requirements
      - '--labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=${COMMIT_SHA},gcb-build-id=${BUILD_ID},gcb-trigger-id=${_TRIGGER_ID}'
      - '--quiet'
    id: 'Deploy'

images:
  - '${_AR_HOSTNAME}/${PROJECT_ID}/cloud-run-source-deploy/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'

options:
  logging: 'CLOUD_LOGGING_ONLY'  # Set logging to Cloud Logging only
  substitutionOption: 'ALLOW_LOOSE'

substitutions:
  _DEPLOY_REGION: 'us-central1'
  _AR_HOSTNAME: 'us-central1-docker.pkg.dev'
  _TRIGGER_ID: '2d8f81c4-48c0-48c6-bf28-2b3cf6c29dab'
  _SERVICE_NAME: 'pwa-server'
  REPO_NAME: 'debtfreeplanner'

tags:
  - 'gcp-cloud-build-deploy-cloud-run'
  - 'gcp-cloud-build-deploy-cloud-run-managed'
  - 'pwa-server'
