steps:
  # Step 1: Clean up unnecessary files and directories
  - name: "ubuntu"
    id: "Clean Up Root and Unnecessary Apps"
    entrypoint: bash
    args:
      - "-c"
      - |
        set -e
        echo "==== Step 1: Cleaning Up Root and Unnecessary Files ===="
        
        # Remove root package files
        echo "Deleting root package.json, pnpm-lock.yaml, and pnpm-workspace.yaml..."
        rm -f package.json pnpm-lock.yaml pnpm-workspace.yaml

        # Remove unnecessary directories
        echo "Deleting apps/public-site and apps/pwa-server directories..."
        rm -rf apps/public-site apps/pwa-server

        # Confirm cleanup
        echo "Remaining directory structure:"
        find . -type d

  # Step 2: Install dependencies for pwa-client and generate pnpm-lock.yaml
  - name: "node:22"
    id: "Install Dependencies for pwa-client"
    entrypoint: bash
    args:
      - "-c"
      - |
        set -e
        echo "==== Step 2: Installing Dependencies for pwa-client ===="

        echo "Installing pnpm globally..."
        npm install -g pnpm

        echo "Initializing a pnpm-lock.yaml for apps/pwa-client..."
        cd apps/pwa-client
        pnpm install --lockfile-only

        # Verify the lockfile is generated
        echo "Verifying pnpm-lock.yaml for pwa-client..."
        ls -l pnpm-lock.yaml

  # Step 3: Build the pwa-client application
  - name: "node:22"
    id: "Build pwa-client"
    entrypoint: bash
    args:
      - "-c"
      - |
        set -e
        echo "==== Step 3: Building the pwa-client Application ===="

        echo "Installing pnpm globally..."
        npm install -g pnpm
        
        cd apps/pwa-client
        pnpm install --frozen-lockfile
        pnpm run build

        # Verify build output
        echo "Verifying .output directory..."
        ls -R .output

  # Step 4: Deploy the pwa-client application to App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy Application"
    entrypoint: bash
    args:
      - "-c"
      - |
        set -e
        echo "==== Step 4: Deploying Application to App Engine ===="
        gcloud app deploy apps/pwa-client/app.yaml --quiet --verbosity=debug

        echo "Deployment complete. Verifying remaining files..."
        ls -R .

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "900s"