steps:
  # Step: Deploy the application to App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy Application"
    entrypoint: bash
    args:
      - "-c"
      - |
        set -e
        echo "==== Step 1: Deploying Application ===="
        gcloud app deploy apps/pwa-client/app.yaml --quiet --verbosity=debug

        echo  "List files in the current directory"
        ls -Rla

options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

timeout: "900s"
