steps:
  # Step 0: Install dependencies and build the project
  - name: "node:22"
    id: "Install Dependencies and Build"
    entrypoint: bash
    args:
      - "-c"
      - |
        set -e
        echo "==== Step 0: Install Dependencies and Build ===="

        echo "Installing pnpm..."
        npm install -g pnpm

        echo "Installing dependencies for @debtfreeplanner/pwa-client..."
        pnpm --filter @debtfreeplanner/pwa-client install --frozen-lockfile

        echo "Building the project..."
        pnpm --filter @debtfreeplanner/pwa-client run build

  # Step 1: Deploy the application to App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy Application"
    entrypoint: bash
    args:
      - "-c"
      - |
        set -e
        echo "==== Step 1: Deploying Application ===="
        gcloud app deploy apps/pwa-client/app.yaml --quiet --verbosity=debug
        
        echo "Final workspace directory structure:"
        ls -R apps/pwa-client/

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "900s"
