steps:
  # Step 0: Install pnpm, install dependencies, and build the project
  - name: 'node:22'
    id: 'Setup, Install Dependencies, and Build'
    dir: 'apps/pwa-client'  # Correct working directory
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        echo "Starting Step 0..."

        echo "Installing pnpm..."
        npm install -g pnpm || { echo "Failed to install pnpm"; exit 1; }

        echo "Installing dependencies..."
        pnpm install || { echo "Failed to install dependencies"; exit 1; }

        echo "Building the project..."
        pnpm run build || { echo "Build failed"; exit 1; }    

        echo "Copying app.yaml to the build output directory..."
        cp app.yaml .output/ || { echo "Failed to copy app.yaml"; exit 1; }

  # Step 1: Verify that the .output directory has the required files
  - name: 'node:22'
    id: 'Verify Output Directory'
    dir: 'apps/pwa-client/.output'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "Verifying .output directory..."
        ls -la
        ls -la server/

  # Step 2: Deploy the application to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Application'
    dir: 'apps/pwa-client/.output'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        echo "Starting Step 2..."
        gcloud app deploy app.yaml --quiet || { echo "Deployment failed"; exit 1; }

options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

timeout: '420s'
