steps:
  # Step 0: Install dependencies and build the project
  - name: "node:22"
    id: "Install Dependencies and Build"
    entrypoint: bash
    args:
      - "-c"
      - |
        set -e  # Exit immediately if a command exits with a non-zero status
        echo "==== Step 0: Install Dependencies and Build ===="

        echo "Initial workspace directory structure:"
        ls -R .

        # Install pnpm globally
        echo "Installing pnpm..."
        npm install -g pnpm || { echo "Failed to install pnpm";}

        # Install dependencies for @debtfreeplanner/pwa-client
        echo "Installing dependencies for @debtfreeplanner/pwa-client..."
        pnpm --filter @debtfreeplanner/pwa-client install --frozen-lockfile || { echo "Failed to install dependencies";}

        # Build the project
        echo "Building the project..."
        pnpm --filter @debtfreeplanner/pwa-client run build || { echo "Build failed";}

        # Validate build output
        if [ ! -f apps/pwa-client/.output/server/index.mjs ]; then
          echo "Build output is incomplete: .output/server/index.mjs not found"
          exit 1
        fi

        # Prune unnecessary files from the .output directory
        echo "Pruning unnecessary files from .output directory..."
        find apps/pwa-client/.output -type f -name '*.map' -delete || { echo "Failed to prune source maps";}
        find apps/pwa-client/.output -type f -name '*.ts' -delete || { echo "Failed to prune TypeScript files";}
        find apps/pwa-client/.output -type f -name '*.json' -delete -not -name 'package.json' || { echo "Failed to prune unnecessary JSON files";}

        # Prepare deployment directory
        echo "Preparing deployment directory..."
        mkdir -p deployment/.output/server
        cp apps/pwa-client/app.yaml deployment/
        cp -r apps/pwa-client/.output/server/* deployment/.output/server/
        cp apps/pwa-client/package.json deployment/
        cp apps/pwa-client/pnpm-lock.yaml deployment/

        # Create .gcloudignore in deployment directory
        echo "Creating .gcloudignore in deployment directory..."
        cat > deployment/.gcloudignore <<EOF
# Ignore everything by default
**

# Include only the necessary files for deployment
!app.yaml
!.output/server/**
!package.json
!pnpm-lock.yaml
EOF

        echo "Deployment directory contents:"
        ls -R deployment/

        # Count the number of files to be deployed
        echo "Counting files to be deployed..."
        DEPLOY_FILE_COUNT=$(find deployment -type f | wc -l)
        echo "Total files to be deployed: $DEPLOY_FILE_COUNT"

        if [ "$DEPLOY_FILE_COUNT" -gt 9999 ]; then
          echo "Error: The deployment contains more than 10,000 files."
          exit 1
        fi

  # Step 1: Deploy the application to App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy Application"
    entrypoint: bash
    args:
      - "-c"
      - |
        set -e
        echo "==== Step 1: Deploying Application ===="
        gcloud app deploy deployment/app.yaml --quiet --verbosity=debug --stop-previous-version

options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

timeout: "1200s"
