steps:
  # Step 0: Install pnpm, install dependencies, and build the project
  - name: 'node:22'
    id: 'Setup, Install Dependencies, and Build'
    dir: '${_APP_DIR:-apps/pwa-client}'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "==== Step 0: Setup, Install Dependencies, and Build ===="

        echo "Installing pnpm..."
        npm install -g pnpm || { echo "Failed to install pnpm"; exit 1; }

        echo "Installing dependencies..."
        pnpm install --frozen-lockfile || { echo "Failed to install dependencies"; exit 1; }

        echo "Building the project..."
        pnpm run build || { echo "Build failed"; exit 1; }

        if [ ! -d .output ] || [ ! -d .output/server ]; then
          echo "Build output is incomplete";
        fi

        echo "Copying app.yaml..."
        cp app.yaml .output/ || { echo "Failed to copy app.yaml"; exit 1; }

  # Step 1: Deploy the application to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Application'
    dir: '${_APP_DIR:-apps/pwa-client}/.output'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "==== Step 1: Deploying Application ===="
        gcloud app deploy app.yaml --quiet

options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

timeout: '420s'

substitutions:
  _APP_DIR: 'apps/pwa-client'
