steps:
  # Step 0: Install pnpm, install dependencies, and build the project
  - name: 'node:22'
    id: 'Setup, Install Dependencies, and Build'
    dir: 'apps/pwa-client'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        echo "==== Step 0: Setup, Install Dependencies, and Build ===="
        
        echo "Installing pnpm..."
        npm install -g pnpm || { echo "Failed to install pnpm"; exit 1; }
        
        echo "Installing dependencies..."
        pnpm install || { echo "Failed to install dependencies"; exit 1; }
        
        echo "Building the project..."
        pnpm run build || { echo "Build failed"; exit 1; }
        
        echo "Copying app.yaml to the build output directory..."
        cp app.yaml .output/ || { echo "Failed to copy app.yaml"; exit 1; }
        
        echo "Listing contents of .output directory..."
        ls -la .output

  # Step 1: Verify that the .output directory has the required files
  - name: 'node:22'
    id: 'Verify Output Directory'
    dir: 'apps/pwa-client/.output'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "==== Step 1: Verifying .output Directory ===="
        echo "Listing contents of .output:"
        ls -la
        
        echo "Checking for server/index.mjs..."
        if [ ! -f server/index.mjs ]; then
          echo "Error: server/index.mjs is missing."
        fi

  # Step 2: Deploy the application to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Application'
    dir: 'apps/pwa-client/.output'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        echo "==== Step 2: Deploying Application ===="
        gcloud app deploy app.yaml --quiet || { echo "Deployment failed"; exit 1; }

options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

timeout: '600s'
