steps:
  # Step 0: Install pnpm, install dependencies, and build the project
  - name: 'node:22'
    id: 'Setup, Install Dependencies, and Build'
    dir: 'apps/pwa-client'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        echo "[Step 0] Installing pnpm..."
        npm install -g pnpm || { echo "Failed to install pnpm"; exit 1; }

        echo "[Step 0] Installing dependencies..."
        pnpm install || { echo "Failed to install dependencies"; exit 1; }

        echo "[Step 0] Building the project..."
        pnpm run build || { echo "Build failed"; exit 1; }

        echo "[Step 0] Copying app.yaml to the build output directory..."
        cp app.yaml .output/ || { echo "Failed to copy app.yaml"; exit 1; }

        echo "[Step 0] Build complete. Listing contents of .output directory..."
        ls -la .output

  # Step 1: Verify that the .output directory has the required files
  - name: 'node:22'
    id: 'Verify Output Directory'
    dir: 'apps/pwa-client/.output'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        echo "[Step 1] Verifying .output directory contents..."
        echo "[Step 1] Root contents:"
        ls -la
        echo "[Step 1] Server contents:"
        ls -la server

  # Step 2: Deploy the application to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Application'
    dir: 'apps/pwa-client/.output'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        echo "[Step 2] Starting deployment..."
        gcloud app deploy app.yaml --quiet || { echo "Deployment failed"; exit 1; }
        echo "[Step 2] Deployment completed successfully."

options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

timeout: '420s'
