steps:
  # Step 1: Install pnpm and dependencies, then build the project
  - name: 'node:22'
    id: 'Install pnpm, dependencies, and build'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "Installing pnpm..."
        npm install -g pnpm

        echo "Installing dependencies..."
        pnpm install

        echo "Running build..."
        pnpm run build

  # Step 2: Deploy application
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy application'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "Deploying application..."
        cd dist # Adjust this if necessary
        gcloud app deploy

options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

timeout: '1200s' # Adjust as needed
