steps:
  # Step 0: Install pnpm, install dependencies, and build the project
  - name: 'node:22'
    id: 'Setup, Install Dependencies, and Build'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "Installing pnpm..."
        npm install -g pnpm

        echo "Installing dependencies..."
        pnpm install

        echo "Building the project..."
        pnpm run build

        echo "Copying app.yaml to the build output directory..."
        cp apps/pwa-client/app.yaml apps/pwa-client/.output/

        echo "Verifying app.yaml in the build output directory..."
        cat apps/pwa-client/.output/app.yaml

  # Step 1: Deploy application
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy application'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "Deploying application..."
        cd apps/pwa-client/.output
        gcloud app deploy app.yaml --quiet

options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

timeout: '1200s'
