steps:
  # Step 0: Install dependencies and build the project
  - name: "node:22"
    id: "Install Dependencies and Build"
    entrypoint: bash
    args:
      - "-c"
      - |
        set -e
        echo "==== Step 0: Install Dependencies and Build ===="

        echo "Installing pnpm..."
        npm install -g pnpm

        echo "Installing dependencies for @debtfreeplanner/pwa-client..."
        pnpm --filter @debtfreeplanner/pwa-client install --frozen-lockfile

        echo "Building the project..."
        pnpm --filter @debtfreeplanner/pwa-client run build

  # Step 1: Deploy the application to App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy Application"
    entrypoint: bash
    args:
      - "-c"
      - |
        set -e
        echo "==== Step 1: Deploying Application ===="

        echo "Listing Current working directory...."
        pwd

        echo "Listing Contents of apps/pwa-client/.output/server Recursively..."
        #ls -Rla apps/pwa-client/.output/server

        echo "Deploying the application to App Engine..."
        gcloud app deploy apps/pwa-client/app.yaml --quiet --verbosity=debug

options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

timeout: "900s"
