steps:
  - name: "node:22"
    id: "Install Dependencies and Build"
    entrypoint: bash
    args:
      - "-c"
      - |
        set -e
        echo "==== Step 1: Installing Dependencies ===="
        npm install -g pnpm
        pnpm --filter @debtfreeplanner/pwa-client install --frozen-lockfile
        echo "==== Step 2: Building Application ===="
        pnpm --filter @debtfreeplanner/pwa-client run build
        echo "==== Build Completed. Verifying Output ===="
        ls -l apps/pwa-client

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy Application"
    entrypoint: bash
    args:
      - "-c"
      - |
        set -e
        echo "==== Step 1: Deploying Application ===="
        gcloud app deploy apps/pwa-client/app.yaml --quiet --verbosity=debug

        echo  "List all contents in the current directory"
        ls -Rla apps/pwa-client

        echo  "List files in the current directory"
        ls -l apps/pwa-client


options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

timeout: "900s"
