steps:
  # Step 0: Install dependencies, build the project, and prepare deployment files
  - name: "node:22"
    id: "Install-Build-Prepare"
    entrypoint: bash
    args:
      - "-c"
      - |
        set -e
        echo "==== Step 0: Install Dependencies, Build, and Prepare ===="
        
        echo "Installing pnpm..."
        npm install -g pnpm

        echo "Installing dependencies for @debtfreeplanner/pwa-client..."
        pnpm install --frozen-lockfile

        echo "Building the project..."
        pnpm run build
        
        # Validate build output
        echo "Validating build output..."
        if [ ! -f .output/server/index.mjs ]; then
          echo "Build output is incomplete: .output/server/index.mjs not found"
        else
          echo "Build output validated: .output/server/index.mjs found"
        fi

  # Step 1: Prepare Deployment Directory
  - name: "ubuntu"
    id: "Prepare-Deployment"
    entrypoint: bash
    args:
      - "-c"
      - |
        set -e
        echo "==== Step 1: Prepare Deployment Directory ===="
        mkdir deployment
        cp app.yaml deployment/
        cp -r .output deployment/
        cp package.json deployment/
        cp pnpm-lock.yaml deployment/

        echo "Deployment directory contents:"
        ls -R deployment/

  # Step 2: Deploy the application to App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy Application"
    entrypoint: bash
    args:
      - "-c"
      - |
        set -e
        echo "==== Step 2: Deploying Application ===="
        cd deployment
        gcloud app deploy app.yaml --quiet --verbosity=debug --stop-previous-version

options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

timeout: "1200s"
