options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: node:22
    entrypoint: bash
    args:
      - '-c'
      - |
        npm install -g pnpm
        pnpm install
        pnpm run build
        # Copy app.yaml to the build output directory
        cp app.yaml dist/
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd dist
        gcloud config set app/cloud_build_timeout 1600
        gcloud app deploy --quiet
timeout: '1600s'