steps:
  - name: "node:22"
    id: "Install Dependencies and Build"
    entrypoint: bash
    args:
      - "-c"
      - |
        set -e
        echo "Installing pnpm..."
        npm install -g pnpm

        echo "Installing dependencies for @debtfreeplanner/pwa-client..."
        pnpm --filter @debtfreeplanner/pwa-client install --frozen-lockfile

        echo "Building the project..."
        pnpm --filter @debtfreeplanner/pwa-client run build

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy Application"
    entrypoint: bash
    args:
      - "-c"
      - |
        set -e

        echo "Copying .output/ to deployment directory..."
        cp -R .output/ ./deploy/

        echo "Deploying application..."
        gcloud app deploy apps/pwa-client/app.yaml --quiet --verbosity=debug --stop-previous-version

options:
  logging: CLOUD_LOGGING_ONLY
timeout: "1200s"
